#!/bin/sh

# Need suspend sink Pulseaudio when system resume and suspend.

. "${PM_FUNCTIONS}"

case $1 in
	suspend)
		sudo -u weston PULSE_RUNTIME_PATH=/run/user/1000/pulse pactl suspend-sink true
		;;
	thaw|resume)
		sudo -u weston PULSE_RUNTIME_PATH=/run/user/1000/pulse pactl suspend-sink false
		;;
	*) exit $NA
		;;
esac

