#!/bin/sh

# Pulseaudio need suspend/resume

. "${PM_FUNCTIONS}"

case $1 in
	suspend)
		sudo -u weston PULSE_RUNTIME_PATH=/run/user/1000/pulse pactl suspend-sink true
		;;
	resume)
		sleep 1.5
		sudo -u weston PULSE_RUNTIME_PATH=/run/user/1000/pulse pactl suspend-sink false
		;;
	*) exit $NA
		;;
esac


